// Do not modify this file directly.
// This file is automatically generated by the build system to ensure that all scripts are linked into the final executable.

#include "FlexScripting/scriptregistry.h"

extern ScriptEntry reg_ECSTestScript;
extern ScriptEntry reg_IntManagerTestScript;
extern ScriptEntry reg_ComponentTestScript;

void ForceLinkScripts()
{
  if (false)
  {
    reg_ECSTestScript.name;
    reg_IntManagerTestScript.name;
    reg_ComponentTestScript.name;
  }
}